name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  analyze:
    name: Analyze Flutter Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Analyzer
        run: flutter analyze

  build-android:
    name: Build Android APK
    needs: analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS IPA
    needs: analyze
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS (no code signing)
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Folder
        uses: actions/upload-artifact@v3
        with:
          name: ios-release
          path: build/ios/iphoneos/